name: Big Blue Helm Action
description: Deploys a helm chart
author: Big Blue Swim School
icon: box
color: blue-dark
inputs:
  release:
    description: Helm release name. Will be combined with track if set. (required)
  namespace:
    description: Kubernetes namespace name. 
  chart:
    description: Helm chart path included in this repository. (required)
  values:
    description: Helm chart values (YAML or JSON String)
runs:
  using: docker
  image: Dockerfile